---
- hosts: monthend
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  
  tasks:
  - name: Execute the uptime script
    script: roles/common/files/uptime.sh
    register: result

  - debug: 
    var: result
    verbosity: 4

  - name: Run with a raw module instead
    raw: uptime
    register: out

  - debug: 
    msg: "{{out.stdout}}"
