---
- hosts: monthend
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no

  tasks:
  - name: Create the uptime wrapper shell script
    copy: 
      src: roles/common/files/uptime.sh
      dest: /tmp/uptime.sh  
      mode: 0755
  - name: Validate file has been copied
    shell: cat /tmp/uptime.sh
  - name: Execute the uptime script on target
    script: /tmp/uptime.sh
  - name: Test dump http conf file
    template:
      src: roles/common/templates/httpd.j2
      dest: /tmp/httpd.conf